var bin_data ;
var terminal ;
var terminal_line ;
var resultview ;
var textview ;
var inodeview ;
var superblockview ;
var binaryview ;
var runview ;
var argview ;
var traceview ;
var editview ;
var savebutton ;
var reloadbutton ;
var runbutton ;
var superblock ;
var loaded ;
var edit_inode ;
var current_i_number ;
var current_name ;
var current_dir_i_number ;
var pdp11 ;
var trace ;
var stdin = String( ) ;
var stdout ;
var u_name ;
var u_dir ;
var u_index ;
var ps_stack = new Array( ) ;
var pc_stack = new Array( ) ;
var sp_stack = new Array( ) ;
var r5_stack = new Array( ) ;
var ret_stack = new Array( ) ;
var proc_stack = new Array( ) ;
var proc_queue = new Array( ) ;
var regs_queue = new Array( ) ;
var ps_queue = new Array( ) ;
